version: '3.5'
services:

    mysql-container:
        image: mysql/mysql-server:latest
        container_name: mysql-builders
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootbuilders
            MYSQL_DATABASE: builders
            MYSQL_USER: builders
            MYSQL_PASSWORD: builders
            TZ: "America/Sao_Paulo"
        volumes:
        - ./db:/docker-entrypoint-initdb.d
        networks:
            - builders-network
            
    app-builders-container:
        image: gutodarbem/img-ms-cliente:1.0
        container_name: app-cliente-builders
        ports:
            - "8202:8202"
        environment:
           MYSQL_HOST: mysql-builders
           MYSQL_PORT: 3306
           MYSQL_DATABASE: builders
           MYSQL_USER_NAME: builders
           MYSQL_PASSWORD: builders
           PROFILES_ACTIVE: prod
        depends_on:
            - mysql-container
        networks:
            - builders-network            
            
networks: 
  builders-network:
    driver: bridge          
